#!/bin/bash
#
# threshold image
#

readarray -t <<<${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS}
path=$(dirname "${MAPFILE[0]}")
file=$(basename "${MAPFILE[0]}")

thr=$(zenity --entry --title="Threshold" --text="Threshold value:")

if [[ $file == *.nii ]]
then
    outname="${file/.nii/"_thr$thr.nii"}"
else
    outname="${file/.nii.gz/"_thr$thr.nii.gz"}"
fi

fslmaths ${MAPFILE[0]} -nan -thr $thr ${path}/$outname

if test -f "${path}/$outname"; then
    notify-send "Done: $outname"
else
    notify-send "Thresholding error"
fi


